package com.goodlinks.model;
// Generated Nov 2, 2018 6:00:00 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic implements java.io.Serializable {

	private static final long serialVersionUID = 5489036131004354812L;
	private Integer id;
	private Subject subject;
	private String name;
	private String description;
	private Set<SubTopic> subTopics = new HashSet<>(0);

	public Topic() {
	}

	public Topic(Subject subject, String name, String description, Set<SubTopic> subTopics) {
		this.subject = subject;
		this.name = name;
		this.description = description;
		this.subTopics = subTopics;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<SubTopic> getSubTopics() {
		return this.subTopics;
	}

	public void setSubTopics(Set<SubTopic> subTopics) {
		this.subTopics = subTopics;
	}

}
