package com.goodlinks.model;
// Generated Nov 2, 2018 6:00:00 PM by Hibernate Tools 5.3.0.Beta2

/**
 * WebLink generated by hbm2java
 */
public class WebLink implements java.io.Serializable {

	private static final long serialVersionUID = -6901854453654205844L;
	private Integer id;
	private SubTopic subTopic;
	private String url;
	private String description;

	public WebLink() {
	}

	public WebLink(SubTopic subTopic, String url, String description) {
		this.subTopic = subTopic;
		this.url = url;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SubTopic getSubTopic() {
		return this.subTopic;
	}

	public void setSubTopic(SubTopic subTopic) {
		this.subTopic = subTopic;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
